images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('', views.image_list, name='list'),
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
]

socialknight/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse


class Image(models.Model):
    class Meta:
        ordering = ('-created',)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created', on_delete=models.CASCADE)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)
    title = models.CharField(max_length=170)
    slug = models.CharField(max_length=200)
    url = models.URLField(null=True)
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

images/forms.py
from urllib import request
from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify
from .models import Image


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            'url': forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg']
        url_extension = url.rsplit('.', 1)[1].lower()
        if url_extension not in valid_extensions:
            raise forms.ValidationError('The given file does not match valid image extensions.')
        return url

    def save(self, force_insert=False, force_update=False, commit=True):
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.', 1)[1].lower()
        image_name = f'{name}.{extension}'
        response = request.urlopen(image_url)
        image.image.save(image_name, ContentFile(response.read()), save=False)
        if commit:
            image.save()

        return image

images/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse, HttpRequest, HttpResponseBadRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from .forms import ImageCreateForm
from .models import Image
from common.decorators import require_ajax

@login_required
def image_create(request):
    if request.method == 'POST':
        image_form = ImageCreateForm(data=request.POST)
        if image_form.is_valid():
            cd = image_form.cleaned_data
            new_image = image_form.save(commit=False)
            new_image.user = request.user
            new_image.save()
            messages.success(request, 'Image added successfully')
            return redirect(new_image.get_absolute_url())
    else:
        image_form = ImageCreateForm(data=request.GET)

    return render(
        request,
        'images/image/create.html',
        {
            'form': image_form,
            'section': 'images'
        }
    )


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)

    context = {
        'section': 'images',
        'image': image
    }
    return render(request, 'images/image/detail.html', context)


@login_required
@require_POST
@require_ajax
def image_like(request):
    json_data = json.loads(request.body)
    image_id = json_data.get('id')
    action = json_data.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Exception as e:
            pass

    return JsonResponse({'status': 'error'})


def image_list(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    json_data = json.loads(request.body) if is_ajax else {}
    page = json_data.get('page') if is_ajax else request.GET.get('page')
    images = Image.objects.all()
    paginator = Paginator(images, 8)

    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if is_ajax:
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)

    if is_ajax:
        return render(request,
                      'images/image/list_ajax.html',
                      {'section': 'images', 'images': images})

    return render(request,
                  'images/image/list.html',
                  {'section': 'images', 'images': images})

images/templates/images/image/create.html
{% extends 'images/image/main_images.html' %}
{% block title %}Bookmark an image{% endblock %}
{% comment %}
http://127.0.0.1:8000/images/create/?title=%20Django%20and%20%20Duke&url=https://picjumbo.com/wp-content/uploads/beautiful-tuscan-landscape-around-pienza-town-italy-1080x720.jpg
{% endcomment %}
{% block content %}
    <h1>Bookmark an image</h1>
    <img src="{{ request.GET.url }}"
         class="image-preview"
    >
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit"
               value="Bookmark it!"
        >
    </form>
{% endblock %}

images/templates/images/image/detail.html
{% extends 'images/image/main_images.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}{{ image.title }}{% endblock %}
{% block content %}
    {% with total_likes=image.users_like.count users_like=image.users_like.all %}
        <header id="header">
            <h2 class="text-info">{{ image.title }}</h2>
            <div class="image-likes">
                <span class="total-likes">{{ total_likes }}</span> like{{ total_likes|pluralize }}
            </div>
        </header>
        <hr>
        <div class="image-container">
            <img src="{% thumbnail image.image 500x0 %}"
                 alt="image-url"
                 class="image-url"
            >
            <div class="image-detail">
                <div class="image-info">
                    <h5 class="image-description">{{ image.description|linebreaks }}</h5>
                </div>
            </div>
        </div>
        <div class="image-action">
            <a href="#"
               id="like-btn"
               data-id="{{ image.id }}"
               data-link="{% url "images:like" %}"
               data-action="{% if request.user in users_like %}un{% endif %}like"
               class="btn btn-lg btn-info"
            >
                {% if request.user not in users_like %}
                    Like
                {% else %}
                    Unlike
                {% endif %}
            </a>
            <div class="user-list">
                {% for user in users_like %}
                    <div class="user">
                        <img class="user-img"
                             src="{% thumbnail user.profile.photo 100x80 %}"
                        />
                        <p class="user-name">{{ user.first_name }}</p>
                    </div>
                    {% empty %}
                    Nobody likes this image yet.
                {% endfor %}
            </div>
        </div>
    {% endwith %}
{% endblock %}
{% block script %}
    <script src="{% static 'images/js/imageLike.js' %}"></script>
{% endblock %}

images/templates/images/image/list.html
{% extends 'images/image/main_images.html' %}
{% load static %}
{% block title %}Images bookmarked{% endblock %}
{% block content %}
    <h2 class="text-info">Images bookmarked</h2>
    <div id="image-list">
        {% include "images/image/list_ajax.html" %}
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'images/js/imageList.js' %}"></script>
{% endblock %}

images/templates/images/image/list_ajax.html
{% load thumbnail %}
{% for image in images %}
    <div class="image card" style="width: 15vw">
        {% thumbnail image.image 300x300 crop="smart" as im %}
        <img class="card-img-top" src="{{ im.url }}">
        <div class="card-body">
            <p class="card-title">{{ image.title }}</p>
            <p class="card-text">{{ image.description|linebreaks }}</p>
            <a href="{{ image.get_absolute_url }}"
               class="btn btn-outline-info"
            >
                See Image
            </a>
        </div>
    </div>
{% endfor %}

images/templates/images/image/main_images.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
    <link href="{% static "images/css/image.css" %}"
          rel="stylesheet"
    >
{% endblock %}